"""foo

Revision ID: 4634e842ac70
Revises: ee59b23815d3
Create Date: 2022-11-16 17:38:57.869358

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4634e842ac70'
down_revision = 'ee59b23815d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
