"""parent

Revision ID: f432efb19d1a
Revises: f9b269f8d5f8
Create Date: 2022-11-17 14:10:42.494618

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f432efb19d1a'
down_revision = 'f9b269f8d5f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.drop_constraint('post_reply_id_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'post', ['parent_id'], ['id'])
    op.drop_column('post', 'reply_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('reply_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_reply_id_fkey', 'post', 'post', ['reply_id'], ['id'])
    op.drop_column('post', 'parent_id')
    # ### end Alembic commands ###
